<?xml version="1.0"?>
<robot name="parallel_robot" xmlns:xacro="http://ros.org/wiki/xacro">

	<xacro:macro name="parallel_leg" params="prefix xyz xyz2 rpy1 rpy2 offset_eje:=0 ">

<!--DESCRIPCION DE PIERNAS EXTERNAS DEL ROBOT PARALELO-->
<!--UNION VARIABLE PARA UNIR LA PLATAFORMA FIJA HACIA LAS CRUZETAS-->
		<joint name="${prefix}_joint_1" type="continuous">
			<origin	xyz="${xyz}" rpy="${rpy1}"/>
			<parent link="plataforma_fija"/>
			<child link="${prefix}_cruceta"/>
			<axis xyz="0 1 0"/>
			<limit lower="${-pi/2}" upper="${pi/2}" velocity="0.5" effort="1000"/>
			<dynamics damping="1" friction="1" />	
		</joint>

<!--CRUZETA-->
		<link name="${prefix}_cruceta">
			<inertial>
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<mass value="0.5"/>
				<inertia  ixx="2.854e-05" ixy="1.720e-12" ixz="7.276e-13" 
						 iyy="2.854e-05" iyz="1.137e-13" izz="2.854e-05"/>
			</inertial>

			<collision>
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<geometry>
					<mesh filename="file://$(find parallel_robot)/meshes/Cruzeta.dae"/>
				</geometry>
			</collision>

			<visual>
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<geometry>
					<mesh filename="file://$(find parallel_robot)/meshes/Cruzeta.dae"/>
				</geometry>
			</visual>

		</link>

<!--UNION VARIABLE PARA UNIR LA CRUCETA HACIA LOS CILINDROS-->
		<joint name="${prefix}_joint_2" type="continuous">
			<origin	xyz="${xyz2}" rpy="${rpy2}"/>
			<parent link="${prefix}_cruceta"/>
			<child link="${prefix}_case"/>
			<axis xyz="1 0 0"/>
			<limit lower="${-pi/2}" upper="${pi/2}" velocity="0.5" effort="50"/>
			<dynamics damping="1" friction="1" />		
		</joint>

<!--CILINDRO-->
		<link name="${prefix}_case">
			<inertial>
				<origin	xyz="0 0.02682  0.19864" rpy="0 0 0"/>
				<mass value="1.5"/>
				<inertia iyy="0.094759468" ixx="0.098498932" ixy="0.0" iyz="0.0" ixz="-0.003431442" izz="0.004491336"/>
			</inertial>

			<collision>
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<geometry>
					<mesh filename="file://$(find parallel_robot)/meshes/Cilindro.dae"/>
				</geometry>
			</collision>

			<visual>
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<geometry>
					<mesh filename="file://$(find parallel_robot)/meshes/Cilindro.dae"/>
				</geometry>
			</visual>

		</link> 

<!--UNION PRISMATICA PARA UNIR CILINDRO Y VASTAGO-->
		<joint name="${prefix}_joint_3" type="prismatic">
			<origin	xyz="0 0 ${0.12315 + offset_eje}" rpy="0 0 0"/>
			<parent link="${prefix}_case"/>
			<child link="${prefix}_vastago"/>
			<axis xyz="0 0 1"/>
			<limit 	lower="${4.679004/1000}" upper="${0.3 -4.679004/1000}" velocity="1.1" effort="1000"/>
			<dynamics damping="1" friction="1" />
		</joint>

<!--VASTAGO-->
		<link name="${prefix}_vastago">
			<inertial>
				<origin	xyz="0 0 0.25" rpy="0 0 0"/>
				<mass value="1"/>
				<inertia ixx="0.0389024975" ixy="0.0" ixz="0.0" iyy="0.0389024975" iyz="0.0" izz="0.000354202"/>
			</inertial>

			<collision>
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<geometry>
					<mesh filename="file://$(find parallel_robot)/meshes/Vastago.dae"/>
				</geometry>
			</collision>

			<visual>
				<origin xyz="0 0 0" rpy="0 0 0"/>
				<geometry>
					<mesh filename="file://$(find parallel_robot)/meshes/Vastago.dae"/>
				</geometry>
			</visual>

		</link>
		<!--COLISIONES EN GAZEBO-->	 
		 <gazebo reference="${prefix}_case">
			<selfCollide>true</selfCollide>
		</gazebo>  
		<gazebo reference="${prefix}_vastago">
			<selfCollide>true</selfCollide>
		</gazebo>
		<gazebo reference="${prefix}_cruceta">
			<selfCollide>true</selfCollide>
		</gazebo> 
	</xacro:macro>
</robot>

