controller_manager:
  ros__parameters:
    update_rate: 10000  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    effort_controllers:
      type: effort_controllers/JointGroupEffortController

   
effort_controllers:
  ros__parameters:
    joints:
       
       - act_1_joint_3
       - act_2_joint_3
       - act_3_joint_3
       - act_4_joint_2

    interface_name: effort
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
     